### PR TITLE
Improve `OptunaSearchCV` (accept `Mapping` in addition to `dict` for `param_distributions` and allow use of `OptunaSearchCV` with `cross_val_predict`)

### PR DESCRIPTION
**Pull request by yu9824**
## Motivation

I have two motivations.

1. Accept `Mapping` in addition to `dict` for `param_distributions`.
2. Allow use of `OptunaSearchCV` with `cross_val_predict`.

### 1. Accept `Mapping` in addition to `dict` for `param_distributions`.

Changed the accepted type from `dict` to `Mapping`.

`MappingProxyType` and other types cannot be made to pickle, which causes an error during parallelization, so the specification has been changed to change to `dict` after accepting the `Mapping` type.

### 2. Allow use of `OptunaSearchCV` with `cross_val_predict`.

In scikit-learn's `HasMethods`, `predict` (and related methods) get error because of 'property', so define them as method.

### CODE REVIEW

**Comment by y0z** [comment]
@nabenabe0928 Could you review this PR?

**Review by nabenabe0928 — CHANGES_REQUESTED** [review]
Could you first move back each method to the original location?
Currently, this PR has much more diffs than we need.

Plus, could you give me the steps to reproduce your error?

**Comment by nabenabe0928** [comment]
@yu9824 

So, I, first of all, found the exceptions where your changes do not work:

- https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier.predict_proba
- https://scikit-learn.org/stable/modules/generated/sklearn.tree.ExtraTreeClassifier.html#sklearn.tree.ExtraTreeClassifier.predict_proba

It means we cannot merge this PR as is, so I will close this PR for now.
However, please feel free to open this PR again if you find any other solutions!
Or you can alternatively post an issue for this regard with the steps to reproduce.

**Comment by yu9824** [comment]
Thank you for your review and comment. 

I'll create issues alternatively to show you how to reproduce errors.
And, I'll deal with your comment.

**Comment by yu9824** [comment]
I've created the issues (#171, #173) and the PRs (#172, #174).

I cannot reproduce your error below. Please tell me in the new PRs.

> @yu9824
> 
> So, I, first of all, found the exceptions where your changes do not work:
> 
> * https://scikit-learn.org/stable/modules/generated/sklearn.tree.DecisionTreeClassifier.html#sklearn.tree.DecisionTreeClassifier.predict_proba
> * https://scikit-learn.org/stable/modules/generated/sklearn.tree.ExtraTreeClassifier.html#sklearn.tree.ExtraTreeClassifier.predict_proba
> 
> It means we cannot merge this PR as is, so I will close this PR for now. However, please feel free to open this PR again if you find any other solutions! Or you can alternatively post an issue for this regard with the steps to reproduce.


I appreciate you taking the time to review this.

**Pull request closed without merging**
