### PR TITLE
Remove non oldest and latest Python versions from tests

### PR DESCRIPTION
**Pull request by nabenabe0928**
## Motivation

This PR aims to reduce the runtime of tests at each PR push.
The changes made here are based on [PR#5067](https://github.com/optuna/optuna/pull/5067) in Optuna.

## Description of the changes

The changes are as follows:
1. add a dynamic workflow matrix for each test, and
2. remove non-oldest and non-latest Python versions from each test.

### CODE REVIEW

**Comment by contramundum53** [comment]
https://github.com/optuna/optuna-integration/pull/44/files#diff-bbaa0e42b6fff0e2453feb887cbeb1ef0d5f23f47e8d47bd3eb137b30fd7e616R22
Could you change this line to 3.8?

**Comment by contramundum53** [comment]
Could you also put the remaining versions to scheduled tests as in optuna?

**Comment by nabenabe0928** [comment]
> Could you also put the remaining versions to scheduled tests as in optuna?

I would like to wait [PR#5067](https://github.com/optuna/optuna/pull/5067) in Optuna to be merged for uniformity.
Once it is merged, I will work on this PR using the same or similar code.
Does this work for you, @contramundum53 ?

**Comment by nabenabe0928** [comment]
Change the matrix generation to if statement.

**Comment by HideakiImamura** [comment]
Thanks for the fix. Could you resolve the conflicts?

**Comment by nabenabe0928** [comment]
@HideakiImamura @contramundum53 
Could you check the PR again?

**Review by contramundum53 — APPROVED** [review]
LGTM!

**Pull request merged**
