### PR TITLE
Create the document and run the test to create document in each PR

### PR DESCRIPTION
**Pull request by HideakiImamura**
## Motivation

The current `optuna-integration` module does not have any documents. This PR aims to add the document using Read The Docs, and add a workflow to run the test to create document in each PR.

## Description of the changes

- Add `docs` directory to build the document
- Add `.github/workflows/sphinx-build.yml` to run the CI

### CODE REVIEW

**Comment by HideakiImamura** [comment]
The latest build document is [here](https://optuna-integration.readthedocs.io/en/latest/).

**Comment by HideakiImamura** [comment]
I will do the following as follow-ups.
- Transfer `https://optuna-integration.readthedocs.io/` from `HideakiImamura/optuna-integration` to `optuna/optuna-integration`.
- Enable showing build document in each PR. See [here](https://docs.readthedocs.io/en/stable/pull-requests.html) for more details.

**Comment by HideakiImamura** [comment]
@gen740 Could you review this PR?

**Review by gen740 — COMMENTED** [review]
Almost LGTM! I left a minor comment.

**Comment by gen740** [comment]
There seems to be something wrong with coverage ci.

**Comment by HideakiImamura** [comment]
@gen740 Thanks for the review. I applied your suggestion. PTAL.

> There seems to be something wrong with coverage ci. Coverage is broken.

Agree. It should be fixed, but there is nothing to do with the current PR. Let's discuss this outside this PR.

**Review by gen740 — APPROVED** [review]
LGTM!

**Pull request merged**
