### PR TITLE
Add an option to install integration dependencies via pip

### PR DESCRIPTION
**Pull request by nabenabe0928**
## Motivation

As there was no option to install the dependencies of integration modules, this PR aims to provide such an way.

For example, if you would like to install the dependencies of `optuna_integration.lightgbm`, we can do with:

```shell
$ pip install optuna-integration[lightgbm]
```

## Description of the changes

I added the dependencies of each integration module to `pyproject.toml`.

## To be discussed

- Whether to remove `requirements.txt` from each module
- Whether to add dependencies for the deprecated modules

### CODE REVIEW

**Comment by eukaryo** [comment]
@HideakiImamura Could you review this PR?

**Comment by nabenabe0928** [comment]
This PR relates to the issue in Optuna as well:
- https://github.com/optuna/optuna/issues/5197

**Comment by HideakiImamura** [comment]
Let me confirm the motivation of this PR. Wouldn't using requirements.txt be sufficient to install additional dependencies? How about just adding instructions to use it?

**Comment by nabenabe0928** [comment]
@HideakiImamura 
> How about just adding instructions to use it?

There are several problems for this:
1. First people would not recognize it,
2. Even if people know it, it doesn't mean that people immediately recognize how to reach the files,
3. People need to make too many actions just to install the dependencies, 
4. It's much easier to install the dependencies one by one by checking module not found error, and
5. However, if we check module not found error, people wouldn't know any version constraints,

The primary difference is whether we have the lists of dependencies either in requirements.txt or in pyproject.toml.
It doesn't add any complexity to the codebase while we will acquire the option to install dependencies via pip, i.e., well-defined 1 command.
Another benefit is the enrichment of the error messages as in PR#5498.

For these reasons, I am seeing more benefits for this change rather than downsides.

**Comment by HideakiImamura** [comment]
Please correct me if I'm wrong, but isn't it possible to install with just one command, pip install -r xxx/requirements.txt, as it stands now?

**Comment by nabenabe0928** [comment]
Did you mean something like this?
```
(base) shuhei@EB-B9400CBA:~$ pip install -r optuna-integration/botorch/requirements.txt
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'optuna-integration/botorch/requirements.txt'
```

**Review by HideakiImamura — APPROVED** [review]
LGTM.

**Pull request merged**
