### PR TITLE
Update supported Python versions

### PR DESCRIPTION
**Pull request by c-bata**
## Motivation

Follow-up https://github.com/optuna/optuna-integration/pull/35 and https://github.com/optuna/optuna-integration/pull/170

## Description of the changes

* Update badge
* Update classifiers
* Update docs
* Specify `requires-python` in package metadata

### CODE REVIEW

**Comment by c-bata** [comment]
@nabenabe0928 @kAIto47802 Could you review this PR?

**Comment by nabenabe0928** [comment]
I will check this PR after @kAIto47802 approves it:)

**Review by kAIto47802 — APPROVED** [review]
LGTM!

**Review by nabenabe0928 — APPROVED** [review]
LGTM!

**Pull request merged**
