### PR TITLE
Use `__future__.annotations`

### PR DESCRIPTION
**Pull request by nzw0301**
## Motivation

Resolve https://github.com/optuna/optuna/issues/4508.

## Description of the changes

1. manually add `from __future__ import annotations` to each file except for `__init__.py`, which is I'm not sure
2. run `ruff check . --fix --select UP007,UP006,F401,I002  --unsafe-fixes`
3. replace `from tying import ...` with `from collections.abc import ...` if necessary

Note that the sphinx-build and mypy with Python 3.8 failed when applying the same thing to sklearn. So I've reverted the changes to sklearn as in https://github.com/optuna/optuna-integration/pull/150/commits/22f97fe735421e4ba80df5fe1ab552ff31ea0658.

### CODE REVIEW

**Comment by nzw0301** [comment]
Hi, I'm not able to reproduce the sphinx-build w/ python 3.8 that is used in the current docs CI because my `conda` does not support python 3.8 installation anymore. Locally, `make html` w/ python 3.10 works without any errors. I really appreciate any suggestions to resolve the CI error.

**Comment by HideakiImamura** [comment]
@nzw0301 Could you resolve a conflict?

**Comment by nzw0301** [comment]
@HideakiImamura thank you for letting me know. Sure!

**Comment by nzw0301** [comment]
done

**Review by nabenabe0928 — APPROVED** [review]
Thank you for the PR, LGTM!

**Pull request merged**
