### PR TITLE
Migrate BoTorch integration

### PR DESCRIPTION
**Pull request by y0z**
## Motivation
- Progress https://github.com/optuna/optuna/issues/4484.

## Description of the changes
- Migrate `BoTorchSampler` from optuna.integration.
- Migrate the tests for BoTorchSampler from Optuna ([optuna/integration/botorch.py](https://github.com/optuna/optuna/blob/master/optuna/integration/botorch.py) and a subset of [tests/samplers_tests/test_samplers.py](https://github.com/optuna/optuna/blob/master/tests/samplers_tests/test_samplers.py)).

### CODE REVIEW

**Comment by contramundum53** [comment]
@y0z 
It seems that `BoTorchSampler` is not tested in the current form. Could you add a TODO comment?

**Comment by contramundum53** [comment]
@y0z The coverage says that `BoTorchSampler` is not covered by tests, although you seem to have added `test_samplers`.

**Comment by y0z** [comment]
I fixed the code and test coverage is now fine.

**Comment by contramundum53** [comment]
Thank you, LGTM!

**Pull request merged**
