### PR TITLE
Remove tests for allennlp and chainer

### PR DESCRIPTION
**Pull request by HideakiImamura**
## Motivation

Development has ceased for AllenNLP and Chainer. In this PR, we will gradually cease the use of these functions by eliminating the tests of the integration functions that have been discontinued.

## Description of the changes

- Remove tests for allennlp and chainer

### CODE REVIEW

**Comment by not522** [comment]
@gen740 Could you review this PR?

**Review by gen740 — COMMENTED** [review]
Almost LGTM! Just one more thing to consider. Could this PR also remove CI dependencies like `mpi`?
https://github.com/optuna/optuna-integration/blob/209a3ab4fd26f83218ee757c540346ca6d6a4c0c/.github/workflows/tests.yml#L56
https://github.com/optuna/optuna-integration/blob/209a3ab4fd26f83218ee757c540346ca6d6a4c0c/.github/workflows/checks.yml#L30
https://github.com/optuna/optuna-integration/blob/209a3ab4fd26f83218ee757c540346ca6d6a4c0c/.github/workflows/coverage.yml#L43
https://github.com/optuna/optuna-integration/blob/209a3ab4fd26f83218ee757c540346ca6d6a4c0c/.github/workflows/mac-tests.yml#L58

**Review by gen740 — APPROVED** [review]
LGTM!

**Comment by gen740** [comment]
There are some conflicts; please merge the main branch.

**Pull request merged**
